language: python

services:
  - postgresql
  - mysql

sudo: false

python:
  - "2.6"
  - "2.7"
  - "3.4"

env:
  - TOXENV=py26-1.6.x DB=postgresql
  - TOXENV=py26-1.6.x DB=mysql
  - TOXENV=py26-1.6.x DB=sqlite

  - TOXENV=py27-1.6.x DB=postgresql
  - TOXENV=py27-1.6.x DB=mysql
  - TOXENV=py27-1.6.x DB=sqlite

  - TOXENV=py27-1.7.x DB=postgresql
  - TOXENV=py27-1.7.x DB=mysql
  - TOXENV=py27-1.7.x DB=sqlite

  - TOXENV=py34-1.6.x DB=postgresql
  - TOXENV=py34-1.6.x DB=mysql
  - TOXENV=py34-1.6.x DB=sqlite

  - TOXENV=py34-1.7.x DB=postgresql
  - TOXENV=py34-1.7.x DB=mysql
  - TOXENV=py34-1.7.x DB=sqlite

install:
  - pip install tox

before_script:
  - mysql -e 'create database pytest_django_casperjs_test;'
  - psql -c 'create database pytest_django_casperjs_test;' -U postgres

script:
  - tox -e "$TOXENV"
