language: python

services:
  - postgresql

sudo: false

python:
  - "2.6"
  - "2.7"
  - "3.4"

env:
  matrix:
    - DB=postgres
    - DB=sqlite

before_script:
  - psql -c 'create database pytest_django_casperjs_test;' -U postgres

script:
  - make develop
  - make test
